# tratamento

Tratamento de extrato de conta-corrente Nubank e Cartão XP.

In [1]:
import pandas as pd
import numpy as np

from src.tratamento import *
import warnings

warnings.filterwarnings('ignore')

In [6]:
treat = Tratamento()
treat.tratar_dados()
df = treat.df


df.sort_values('Valor')

,Data,Valor,Tipo,Descrição,flag_receita,flag_fatura_xp,flag_salario,flag_parcela
11,2024-10-09,-9500.00,Reserva - Depósito,Aplicação RDB,False,False,False,False
20,2024-12-11,-9371.52,PIX - Enviado,Transferência enviada pelo Pix - JULIO EMANUEL...,False,False,False,False
31,2024-12-23,-8720.00,Reserva - Depósito,Aplicação RDB,False,False,False,False
4,2024-12-01,-7500.00,Reserva - Depósito,Aplicação RDB,False,False,False,False
8,2024-09-02,-7157.47,Boleto,Pagamento de boleto efetuado - BANCO XP S/A,False,True,False,False
...,...,...,...,...,...,...,...,...
2,2024-10-02,7235.28,PIX - Recebido,Transferência recebida pelo Pix - MATEUS BANDE...,True,False,True,False
23,2024-12-12,9371.52,False,Transferência Recebida - Clarissa Bernardes Ro...,True,False,False,False
10,2024-10-08,10000.00,PIX - Recebido,Transferência recebida pelo Pix - MATEUS BANDE...,True,False,True,False
1,2024-01-02,10000.00,PIX - Recebido,Transferência recebida pelo Pix - MATEUS BANDE...,True,False,True,False
0,2024-08-01,10000.00,PIX - Recebido,Transferência recebida pelo Pix - MATEUS BANDE...,True,False,True,False